Add example for prefetcher Swift
heremaps/here-ios-sdk-examples pull request #210
Opened 2021-08-13 11:24 UTC by LeOric32

2021-08-16 08:47 UTC, dashchak requested changes
Looks like you committed 2 duplicated projects nested in each other. Please fix

2021-08-16 16:09 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +            prefetcher.fetchMapDataForBoundingBox(boundingBox, error: nil)
Please handle error here and in other places of prefetching.
 i.e. when Area is too big, data will not even start prefetching

2021-08-16 16:09 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +
Remove line

2021-08-16 16:09 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +        stops.append(langley)
let stops = [hereBurnaby, langley]

2021-08-16 16:09 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +                return
Please show error to user. Sometime route can not be created

2021-08-16 16:09 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +        mapRoute?.traveledColor = .clear
please remove this line as navigation is not supported in this app

2021-08-16 16:09 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +        self.view.isUserInteractionEnabled = false
Can be extracted to function and reused

2021-08-18 08:35 UTC, LeOric32 commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +            prefetcher.fetchMapDataForBoundingBox(boundingBox, error: nil)
Done

2021-08-18 08:36 UTC, LeOric32 commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +
Done

2021-08-18 08:36 UTC, LeOric32 commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +        stops.append(langley)
Done

2021-08-18 08:36 UTC, LeOric32 commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +        mapRoute?.traveledColor = .clear
Done

2021-08-18 08:36 UTC, LeOric32 commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +        self.view.isUserInteractionEnabled = false
Done

2021-08-18 08:36 UTC, LeOric32 commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +                return
Done

2021-08-18 08:53 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +        static let frame = CGRect(x: 110, y: 200, width: 220, height: 120)
Remove it

2021-08-18 08:53 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +    func mapViewDidDraw(_ mapView: NMAMapView) {
Is not this callback called many times? You can create route in viewDidAppear

2021-08-18 08:53 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +            self.showMessage(title: "Error", message: "Can't estimate area.")
Also include error number

2021-08-18 12:17 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +            self.showMessage(title: "Error", message: "Can't fetch area.")
Show error number

2021-08-18 12:17 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +        showMessage(title: "Success", message: message)
use title depending on "withSuccess success"

2021-08-18 12:17 UTC, dashchak commented on map-data-prefetcher-ios-swift/MapDataPrefetcherApp/ViewController.swift
> +        self.createRoute()
Not needed to use extra method for it

2021-08-18 13:31 UTC, closed without merging